{{- if .Values.memcached.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: memcached
spec:
  type: ExternalName
  externalName: "{{ .Release.Name }}-memcached.{{ .Release.Namespace }}"
{{- else if ne .Values.memcached.serviceFqdn "memcached" }}
---
apiVersion: v1
kind: Service
metadata:
  name: memcached
spec:
  type: ExternalName
  externalName: "{{ .Values.memcached.serviceFqdn }}"
{{- end }}
