{{- if and .Values.persistence.books_pvc.enabled  (not .Values.persistence.books_pvc.customVolume)}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "calibre-web.fullname" . }}-books-pvc
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  accessModes:
    - {{ .Values.persistence.books_pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.books_pvc.storage }}
{{- end }}
