apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "calibre-web.fullname" . }}-conf-pvc
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  accessModes:
    - {{ .Values.conf_pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.conf_pvc.storage }}
