apiVersion: v1
kind: Service
metadata:
  name: {{ include "calibre-web.fullname" . }}-service-web
  labels:
    {{- include "calibre-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "calibre-web.selectorLabels" . | nindent 4 }}
  ports:
    - port: 8083
      targetPort: http
      protocol: TCP
      name: http
