{{- if and (.Values.persistence.enabled) (.Values.backup.enabled) }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "zigbee2mqtt.fullname" . }}-backup
spec:
  schedule: "{{ .Values.backup.cron }}"
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: {{ include "zigbee2mqtt.fullname" . }}-backup-upload
            image: minio/mc
            imagePullPolicy: IfNotPresent
            env:
            - name: M_HOSTNAME
              value: {{ .Values.backup.minio.hostname }}
            - name: M_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.backup.minio.secretName }}
                  key: accesskey
            - name: M_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.backup.minio.secretName }}
                  key: secretkey
            command:
              - /bin/sh
              - -c
            args:
              - mc alias set zigbeebackup $M_HOSTNAME $M_ACCESS_KEY $M_SECRET_KEY;
                mc rm zigbeebackup/{{ .Values.backup.minio.bucketName }}/zigbee2mqtt/{{ include "zigbee2mqtt.fullname" . }}_backup_latest.zip;
                cp /backup/{{ include "zigbee2mqtt.fullname" . }}_backup_*.zip /backup/{{ include "zigbee2mqtt.fullname" . }}_backup_latest.zip;
                mc cp /backup/{{ include "zigbee2mqtt.fullname" . }}_backup_*.zip zigbeebackup/{{ .Values.backup.minio.bucketName }}/zigbee2mqtt/;
            volumeMounts:
            - name: backup-dir
              mountPath: /backup
          initContainers:
          - name: {{ include "zigbee2mqtt.fullname" . }}-backup-compress
            image: "{{ .Values.backup.image.repository }}:{{ .Values.backup.image.tag }}"
            imagePullPolicy: {{ .Values.backup.image.pullPolicy }}
            env:
            - name: MQTT_HOST
              value: "{{ .Values.backup.mqttHost }}"
            - name: ZIP_PATH
              value: "/backup"
            - name: FILENAME_TEMPLATE
              value: "{{ include "zigbee2mqtt.fullname" . }}_backup"
            volumeMounts:
            - name: backup-dir
              mountPath: /backup
          restartPolicy: Never
          volumes:
          - name: backup-dir
            emptyDir: {}
{{- end }}
