apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zigbee2mqtt.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "zigbee2mqtt.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "zigbee2mqtt.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "zigbee2mqtt.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: zigbee2mqtt
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            {{- if .Values.persistence.enabled }}
            - name: ZIGBEE2MQTT_DATA
              value: {{ .Values.persistence.mountPath }}
            {{- end }}
            - name: ZIGBEE2MQTT_CONFIG_FRONTEND # https://github.com/Koenkk/zigbee2mqtt/issues/19713
              value: "false"
            - name: ZIGBEE2MQTT_CONFIG_FRONTEND_PORT
              value: "8080"
            - name: ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC
              value: "zigbee2mqtt"
            - name: ZIGBEE2MQTT_CONFIG_MQTT_INCLUDE_DEVICE_INFORMATION
              value: "true"
            - name: ZIGBEE2MQTT_CONFIG_MQTT_KEEPALIVE
              value: "60"
            - name: ZIGBEE2MQTT_CONFIG_MQTT_REJECT_UNAUTHORIZED
              value: "true"
            - name: ZIGBEE2MQTT_CONFIG_MQTT_VERSION
              value: "5"
            # - name: ZIGBEE2MQTT_CONFIG_MQTT_USER
            #   value: "admin"
            # - name: ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD
            #   value: admin@123
            - name: ZIGBEE2MQTT_CONFIG_PERMIT_JOIN
              value: "false"
            - name: ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_DISCOVERY_TOPIC
              value: homeassistant
            - name: ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_LEGACY_ENTITY_ATTRIBUTES
              value: "false"
            - name: ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_LEGACY_TRIGGERS
              value: "false"
            - name: ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_STATUS_TOPIC
              value: homeassistant/status
            - name: ZIGBEE2MQTT_CONFIG_ADVANCED_LAST_SEEN
              value: ISO_8601
            - name: ZIGBEE2MQTT_CONFIG_ADVANCED_LEGACY_API
              value: "false"
            - name: ZIGBEE2MQTT_CONFIG_ADVANCED_LEGACY_AVAILABILITY_PAYLOAD
              value: "false"
            - name: ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_LEVEL
              value: info
            - name: ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_OUTPUT
              value: '["console"]'
            - name: ZIGBEE2MQTT_CONFIG_AVAILABILITY_ACTIVE_TIMEOUT
              value: "60"
            - name: ZIGBEE2MQTT_CONFIG_AVAILABILITY_PASSIVE_TIMEOUT
              value: "2000"
            - name: ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_LEGACY
              value: "false"
            - name: ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_RETAIN
              value: "true"
            - name: ZIGBEE2MQTT_CONFIG_EXPERIMENTAL_NEW_API
              value: "true"
            - name: ZIGBEE2MQTT_CONFIG_HOMEASSISTANT
              value: "true"
            - name: ZIGBEE2MQTT_CONFIG_MQTT_SERVER
            {{- if ne .Values.mosquitto.serviceFqdn ""  }}
              value: "{{ .Values.mosquitto.serviceFqdn }}"
            {{- else if .Values.mosquitto.enabled }}
              value: "mqtt://{{ .Release.Name }}-mosquitto.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}"
            {{- end }}
            {{- with .Values.env }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: config-data
              mountPath: {{ .Values.persistence.mountPath }}
            {{- if .Values.usb.enabled }}
            - name: usb
              mountPath: /dev/ttyACM0
            - name: udev
              mountPath: /run/udev
            {{- end }}
          livenessProbe:
            httpGet:
              port: http
            initialDelaySeconds: 30
            failureThreshold: 3
            periodSeconds: 60
          readinessProbe:
            httpGet:
              port: http
            initialDelaySeconds: 15
            failureThreshold: 3
            periodSeconds: 30
          startupProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 0
            failureThreshold: 30
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "zigbee2mqtt.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- if .Values.usb.enabled }}
        - name: usb
          hostPath:
            type: CharDevice
            path: {{ .Values.usb.hostPath }}
        - name: udev
          hostPath:
            path: /run/udev
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
