{{- if and .Values.persistence.media.enabled  (not .Values.persistence.media.customVolume)}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "jellyfin.fullname" . }}-media
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.media.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.media.size }}
{{- end }}
