apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  AdGuardHome.yaml: {{ .Values.configmap_config.AdGuardHome.yaml }}
