apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "adguard-home.fullname" . }}-config
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  AdGuardHome.yaml: {{ toYaml .Values.configmap_config }}
