apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "adguard-home.fullname" . }}-work-pvc
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  accessModes:
    - {{ .Values.work_pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.work_pvc.storage }}
