apiVersion: v2
name: private-assistant-skill-orchestrator-py
description: A Helm chart for Kubernetes
type: application
version: 0.2.0
appVersion: "0.2.0"
dependencies:
  - name: postgresql
    version: 15.2.4
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: mosquitto
    version: 0.5.1
    repository: https://stkr22.github.io/helm-charts
    condition: mosquitto.enabled
