apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullstack.fullname" . }}-backend
  labels:
    {{- include "fullstack.backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "fullstack.backend.selectorLabels" . | nindent 4 }}
