apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullstack.fullname" . }}-frontend
  labels:
    {{- include "fullstack.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fullstack.frontend.selectorLabels" . | nindent 4 }}
