apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "airsonicAdvanced.fullname" . }}
  labels:
    {{- include "airsonicAdvanced.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "airsonicAdvanced.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "airsonicAdvanced.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.airsonicAdvanced.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "airsonicAdvanced.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.airsonicAdvanced.media.enabled }}
      initContainers:
        - name: rclone-sync
          image: rclone/rclone:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
          args:
            - rclone sync --config /secret/{{ .Values.airsonicAdvanced.media.rcloneSecretKey }}
              --delete-after --progress --stats 10s
              --check-first {{ .Values.airsonicAdvanced.media.rcloneLocation }} /var/music
          volumeMounts:
          - name: music
            mountPath: /var/music
          - name: rclone-config
            mountPath: /secret/
            readOnly: true
      {{- end }}
      containers:
        - name: airsonic-advanced
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.airsonicAdvanced.image.repository }}:{{ .Values.airsonicAdvanced.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.airsonicAdvanced.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 4040
              protocol: TCP
            - name: dlna
              containerPort: 4041
              protocol: TCP
          env:
            - name: JAVA_OPTS
              value: "-Dserver.forward-headers-strategy=native"
            {{- with .Values.airsonicAdvanced.env }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /login
              port: http
            initialDelaySeconds: 5
            failureThreshold: 4
            timeoutSeconds: 3
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /login
              port: http
            initialDelaySeconds: 5
            failureThreshold: 4
            timeoutSeconds: 3
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            failureThreshold: 60
            timeoutSeconds: 2
            periodSeconds: 5
          volumeMounts:
            - name: config
              mountPath: /var/airsonic
            - name: music
              mountPath: /var/music
          resources:
            {{- toYaml .Values.airsonicAdvanced.resources | nindent 12 }}
      volumes:
        - name: config
          {{- if .Values.airsonicAdvanced.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "airsonicAdvanced.fullname" . }}-config
          {{- else if not .Values.airsonicAdvanced.persistence.enabled }}
          emptyDir: {}
          {{- end }}
        - name: music
          {{- if .Values.airsonicAdvanced.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "airsonicAdvanced.fullname" . }}-music
          {{- else if not .Values.airsonicAdvanced.persistence.enabled }}
          emptyDir: {}
          {{- end }}
        {{- if .Values.airsonicAdvanced.media.enabled }}
        - name: rclone-config
          secret:
              secretName: {{ .Values.airsonicAdvanced.media.rcloneSecretName }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
