{{- if .Values.airsonicAdvanced.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "airsonicAdvanced.fullname" . }}-music
  labels:
    {{- include "airsonicAdvanced.labels" . | nindent 4 }}
spec:
  accessModes:
  - {{ .Values.airsonicAdvanced.persistence.musicAccessMode }}
  resources:
    requests:
      storage: {{ .Values.airsonicAdvanced.persistence.musicSize }}
{{- end }}
