{{- if .Values.airsonicAdvanced.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "airsonicAdvanced.fullname" . }}-config
  labels:
    {{- include "airsonicAdvanced.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.airsonicAdvanced.persistence.configSize }}
{{- end }}
