{{- $clusterDomain := .Values.clusterDomain | default "" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "private-assistant.fullname" . }}-bridge-config
  labels:
    {{- include "private-assistant.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{ include "private-assistant.config" . | nindent 4 }}
    {{ include "private-assistant.bridgeConfig" . | nindent 4 }}
    {{- .Values.bridge.config | nindent 4 }}
