{{- $clusterDomain := .Values.clusterDomain | default "" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "private-assistant.fullname" . }}-coordinator-config
  labels:
    {{- include "private-assistant.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{ include "private-assistant.config" . }}
    {{- .Values.coordinator.config | nindent 4 }}
