apiVersion: v1
kind: Service
metadata:
  name: {{ include "private-assistant.fullname" . }}-ground-station
  labels:
    {{- include "private-assistant.labels" . | nindent 4 }}
spec:
  type: {{ .Values.groundStation.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: ground-station
    {{- include "private-assistant.selectorLabels" . | nindent 4 }}
