{{- range .Values.skills.activeSkills }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "private-assistant.fullname" $ }}-{{ .name }}
  labels:
    {{- include "private-assistant.labels" $ | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "private-assistant.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      labels:
        {{- include "private-assistant.labels" $ | nindent 8 }}
	{{- with $.Values.podLabels }}
        {{- toYaml $ | nindent 8 }}
        {{- end }}
    spec:
      {{- if .image.pullSecret }}
      imagePullSecrets:
        - name: {{ .image.pullSecret }}
      {{- end }}
      serviceAccountName: {{ include "private-assistant.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .name }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          env:
            - name: PRIVATE_ASSISTANT_CONFIG_PATH
              value: /config/
            {{- toYaml $.Values.globalEnv | nindent 12 }}
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
          volumeMounts:
            - name: base-config
              mountPath: /config/base_config.yaml
              subPath: base_config.yaml
              readOnly: true
            - name: skill-config
              mountPath: /config/skill_config.yaml
              subPath: skill_config.yaml
              readOnly: true
      volumes:
        - name: base-config
          secret:
            secretName: {{ include "private-assistant.fullname" $ }}-base-config
        - name: skill-config
          secret:
            secretName: {{ .configSecretName }}
---
{{- end }}
