apiVersion: v1
kind: Service
metadata:
  name: {{ include "private-assistant.fullname" . }}-tts-engine
  labels:
    {{- include "private-assistant.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ttsEngine.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "private-assistant.selectorLabels" . | nindent 4 }}
