# Default values for homeassistant.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/home-assistant/home-assistant
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

config: |-
  default_config:

  # Text to speech
  tts:
    - platform: google_translate
  {{- if .Values.postgres.enabled }}
  recorder:
    purge_keep_days: 30
    commit_interval: 3
    db_url: postgresql://PGUSER:PGPASSWORD@{{ template "homeassistant.fullname" . }}-db/ha_recorder
  {{- end }}
  http:
    use_x_forwarded_for: true
    trusted_proxies:
      - 10.0.0.0/8
      - 192.168.0.0/16

postgres:
  enabled: true
  image:
    repository: postgres
    tag: 14.2-alpine
    pullPolicy: IfNotPresent
  user: homeassistant
  password: savepassword
  existingSecret: ""
  env: []
  resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  persistence:
    enabled: true
    existingClaim: ""
    size: 2Gi
    accessMode: ReadWriteOnce

env: []

persistence:
  enabled: false
  size: 2Gi

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8123

ingress:
  enabled: true
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: homeassistant.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # limits:
  #   cpu: 240m
  #   memory: 256Mi
  # requests:
  #   cpu: 120m
  #   memory: 128Mi


nodeSelector: {}

tolerations: []

affinity: {}
