apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pigallery2.fullname" . }}
  labels:
    {{- include "pigallery2.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "pigallery2.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pigallery2.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.pigallery2.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pigallery2.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.pigallery2.media.enabled }}
      initContainers:
        - name: rclone-sync
          image: rclone/rclone:1.58.1
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
          args:
            - rclone sync --config /secret/{{ .Values.pigallery2.media.rcloneSecretKey }}
              --delete-after --progress --stats 10s
              --check-first {{ .Values.pigallery2.media.rcloneLocation }} /media
          volumeMounts:
          - name: media
            mountPath: /media
          - name: rclone-config
            mountPath: /secret/
            readOnly: true
      {{- end }}
      containers:
        - name: pigallery2
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.pigallery2.image.repository }}:{{ .Values.pigallery2.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.pigallery2.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: NODE_ENV
              value: production
            - name: Server-Database-type
              value: mysql
            - name: MYSQL_HOST
              value: "{{ template "pigallery2.fullname" . }}-db"
            - name: MYSQL_DATABASE
              value: pigallery2
            - name: MYSQL_USERNAME
              {{- if .Values.db.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.existingSecret }}
                  key: mysql-username
              {{- else }}
              value: {{ .Values.db.user }}
              {{- end }}
            - name: MYSQL_PASSWORD
              {{- if .Values.db.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.existingSecret }}
                  key: mysql-password
              {{- else }}
              value: {{ .Values.db.password }}
              {{- end }}
            {{- with .Values.pigallery2.env }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /heartbeat
              port: http
            initialDelaySeconds: 60
            failureThreshold: 3
            periodSeconds: 40
          readinessProbe:
            httpGet:
              path: /heartbeat
              port: http
            initialDelaySeconds: 60
            failureThreshold: 3
            periodSeconds: 40
          volumeMounts:
            - name: config
              mountPath: /app/data/
            - name: media
              mountPath: /app/data/images
              readOnly: true
          resources:
            {{- toYaml .Values.pigallery2.resources | nindent 12 }}
      volumes:
        - name: config
          {{- if .Values.pigallery2.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "pigallery2.fullname" . }}-config
          {{- else if not .Values.pigallery2.persistence.enabled }}
          emptyDir: {}
          {{- end }}
        - name: media
          {{- if .Values.pigallery2.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "pigallery2.fullname" . }}-media
          {{- else if not .Values.pigallery2.persistence.enabled }}
          emptyDir: {}
          {{- end }}
        {{- if .Values.pigallery2.media.enabled }}
        - name: rclone-config
          secret:
              secretName: {{ .Values.pigallery2.media.rcloneSecretName }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
