{{- if .Values.pigallery2.persistence.config.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pigallery2.fullname" . }}-config
  labels:
    {{- include "pigallery2.labels" . | nindent 4 }}
spec:
  accessModes:
  - {{ .Values.pigallery2.persistence.config.accessMode }}
  resources:
    requests:
      storage: {{ .Values.pigallery2.persistence.config.size }}
{{- end }}
