{{- if .Values.pigallery2.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pigallery2.fullname" . }}-media
  labels:
    {{- include "pigallery2.labels" . | nindent 4 }}
spec:
  accessModes:
  - {{ .Values.pigallery2.persistence.mediaAccessMode }}
  resources:
    requests:
      storage: {{ .Values.pigallery2.persistence.mediaSize }}
{{- end }}
