apiVersion: v1
kind: Service
metadata:
  name: {{ include "pigallery2.fullname" . }}-web
  labels:
    {{- include "pigallery2.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pigallery2.selectorLabels" . | nindent 4 }}
