apiVersion: v1
kind: Service
metadata:
  name: {{ template "pigallery2.fullname" . }}-db
  labels:
    {{- include "pigallery2.db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: mariadb
      port: 3306
      targetPort: db
  selector:
    {{- include "pigallery2.db.selectorLabels" . | nindent 4 }}
