apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "navidrome.fullname" . }}
  labels:
    {{- include "navidrome.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "navidrome.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "navidrome.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.navidrome.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "navidrome.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.navidrome.media.enabled }}
      initContainers:
        - name: rclone-sync
          image: rclone/rclone:1.58.1
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
          args:
            - rclone sync --config /secret/{{ .Values.navidrome.media.rcloneSecretKey }}
              --delete-after --progress --stats 10s
              --check-first {{ .Values.navidrome.media.rcloneLocation }} /music
          volumeMounts:
          - name: music
            mountPath: /music
          - name: rclone-config
            mountPath: /secret/
            readOnly: true
      {{- end }}
      containers:
        - name: navidrome
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.navidrome.image.repository }}:{{ .Values.navidrome.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.navidrome.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 4533
              protocol: TCP
          env:
            - name: ND_SCANSCHEDULE
              value: "1h"
            - name: ND_LOGLEVEL
              value: "info"
            - name: ND_SESSIONTIMEOUT
              value: "24h"
            {{- with .Values.navidrome.env }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            failureThreshold: 4
            timeoutSeconds: 3
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            failureThreshold: 4
            timeoutSeconds: 3
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            failureThreshold: 60
            timeoutSeconds: 2
            periodSeconds: 5
          volumeMounts:
            - name: config
              mountPath: /data
            - name: music
              mountPath: /music
          resources:
            {{- toYaml .Values.navidrome.resources | nindent 12 }}
      volumes:
        - name: config
          {{- if .Values.navidrome.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "navidrome.fullname" . }}-config
          {{- else if not .Values.navidrome.persistence.enabled }}
          emptyDir: {}
          {{- end }}
        - name: music
          {{- if .Values.navidrome.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "navidrome.fullname" . }}-music
          {{- else if not .Values.navidrome.persistence.enabled }}
          emptyDir: {}
          {{- end }}
        {{- if .Values.navidrome.media.enabled }}
        - name: rclone-config
          secret:
              secretName: {{ .Values.navidrome.media.rcloneSecretName }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
