{{- if .Values.navidrome.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "navidrome.fullname" . }}-music
  labels:
    {{- include "navidrome.labels" . | nindent 4 }}
spec:
  accessModes:
  - {{ .Values.navidrome.persistence.musicAccessMode }}
  resources:
    requests:
      storage: {{ .Values.navidrome.persistence.musicSize }}
{{- end }}
