{{- if .Values.navidrome.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "navidrome.fullname" . }}-config
  labels:
    {{- include "navidrome.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.navidrome.persistence.configSize }}
{{- end }}
