apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homeassistant.fullname" . }}
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
data:
  configuration.yaml: |
    # Loads default set of integrations. Do not remove.
    default_config:

    # Load frontend themes from the themes folder
    {{- if .Values.postgresql.enabled }}
    recorder:
      purge_keep_days: 30
      commit_interval: 3
      db_url: postgresql://{{ .Values.postgresql.global.postgresql.auth.username }}:{{ .Values.postgresql.global.postgresql.auth.password }}@{{ template "homeassistant.fullname" . }}-postgresql.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}/{{ .Values.postgresql.global.postgresql.auth.database }}
    {{- end }}
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.0.0.0/8
        - 192.168.0.0/16
