apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homeassistant.fullname" . }}
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
data:
  configuration.yaml: |-
    {{- .Values.config | nindent 4 }}
