apiVersion: v1
kind: Service
metadata:
  name: {{ include "homeassistant.fullname" . }}
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 8123
      protocol: TCP
      name: http
  selector:
    {{- include "homeassistant.selectorLabels" . | nindent 4 }}
