apiVersion: v1
kind: Service
metadata:
  name: {{ template "homeassistant.fullname" . }}-db
  labels:
    {{- include "homeassistant.postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: postgresql
      port: 5432
      targetPort: pgdb
  selector:
    {{- include "homeassistant.postgres.selectorLabels" . | nindent 4 }}
