# Default values for pigallery2.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

pigallery2:
  image:
    repository: bpatrik/pigallery2
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  persistence:
    enabled: true
    configSize: 1Gi
    mediaSize: 10Gi
    mediaAccessMode: ReadWriteOnce
    configAccessMode: ReadWriteOnce
  env: []
  resources: {}

db:
  enabled: true
  image:
    repository: mariadb
    tag: "10.7.3"
    pullPolicy: IfNotPresent
  existingSecret: ""
  env: []
  resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  persistence:
    enabled: true
    existingClaim: ""
    size: 2Gi
    accessMode: ReadWriteOnce

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000
  fsGroupChangePolicy: OnRootMismatch
  supplementalGroups:
    - 1000

securityContext:
  capabilities:
    drop:
      - ALL
  runAsUser: 0
  runAsGroup: 0
  runAsNonRoot: false
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false
  privileged: false
  seccompProfile:
    type: RuntimeDefault

service:
  type: ClusterIP

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: pigallery2.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

nodeSelector: {}

tolerations: []

affinity: {}
