clusterDomain: cluster.local

replicaCount: 1

image:
  repository: koenkk/zigbee2mqtt:2.1.3
  pullPolicy: IfNotPresent

mosquitto:
  enabled: true
  serviceFqdn: ""

env: []

persistence:
  enabled: true
  size: 2Gi
  mountPath: /data
  accessMode: ReadWriteOnce
  existingClaim: ""  # Add this field for specifying an existing PVC

usb:
  enabled: false
  hostPath: /dev/ttyACM0

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  privileged: true
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: zigbee2mqtt.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  # limits:
  #   cpu: 210m
  #   memory: 240Mi
  # requests:
  #   cpu: 70m
  #   memory: 80Mi

nodeSelector: {}

tolerations: []

affinity: {}
