replicaCount: 1

image:
  repository: koenkk/zigbee2mqtt
  pullPolicy: IfNotPresent
  tag: ""

env:
  - name: ZIGBEE2MQTT_CONFIG_MQTT_SERVER
    value: mqtt://mosquitto

persistence:
  enabled: true
  size: 2Gi
  mountPath: /data
  accessMode: ReadWriteOnce

usb:
  enabled: false
  hostPath: /dev/ttyACM0

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  privileged: true
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: zigbee2mqtt.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  # limits:
  #   cpu: 210m
  #   memory: 240Mi
  # requests:
  #   cpu: 70m
  #   memory: 80Mi


nodeSelector: {}

tolerations: []

affinity: {}
