apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
data:
  mosquitto.conf: |
    listener {{ .Values.service.port }}
    allow_anonymous true
    persistence true
    persistence_location {{ .Values.persistence.mountPath }}
    autosave_interval 1800
