{{- if .Values.loadBalancer.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mosquitto.fullname" . }}-lb-service
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
  {{- with .Values.loadBalancer.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: LoadBalancer
  ports:
    - port: 1883
      targetPort: mqtt
      name: mqtt
  selector:
    {{- include "mosquitto.selectorLabels" . | nindent 4 }}
{{- end }}
