{{- if not .Values.postgres.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fireflyiii.fullname" . }}-db
  labels:
    {{- include "fireflyiii.postgres.labels" . | nindent 4 }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
type: Opaque
data:
  postgresql-username: {{ template "fireflyiii.postgres.user" . }}
  postgresql-password: {{ template "fireflyiii.postgres.password" . }}
{{- end }}
