{{- if .Values.frontend.cronjob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "fireflyiii.fullname" . }}-frontend-cron
  labels:
    {{- include "fireflyiii.labels" . | nindent 4 }}
spec:
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          {{- with .Values.frontend.cronjob.imagePullSecrets }}
          imagePullSecrets: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.frontend.cronjob.podSecurityContext }}
          securityContext: {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: frontend-cronjob
              {{- with .Values.frontend.cronjob.securityContext }}
              securityContext: {{- toYaml . | nindent 16 }}
              {{- end }}
              image: "{{ .Values.frontend.cronjob.image.repository }}:{{ .Values.frontend.cronjob.image.tag }}"
              imagePullPolicy: {{ .Values.frontend.cronjob.image.pullPolicy }}
              env:
                - name: FIREFLY_III_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: {{ template "fireflyiii.fullname" . }}-frontend
                      key: cron-token
              command:
                - /usr/bin/curl
              args:
                - --silent
                - --show-error
                - --fail
                - "http://{{ include "fireflyiii.fullname" . }}/api/v1/cron/$(FIREFLY_III_TOKEN)"
              {{- with .Values.frontend.cronjob.resources }}
              resources: {{- toYaml . | nindent 16 }}
              {{- end }}
          {{- with .Values.frontend.cronjob.nodeSelector }}
          nodeSelector: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.frontend.cronjob.affinity }}
          affinity: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.frontend.cronjob.tolerations }}
          tolerations: {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
