{{- if not .Values.frontend.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fireflyiii.fullname" . }}-frontend
  labels:
    {{- include "fireflyiii.labels" . | nindent 4 }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
type: Opaque
data:
  appKey: {{ template "fireflyiii.frontend.appKey" . }}
  cronToken: {{ template "fireflyiii.frontend.cronToken" . }}
{{- end }}
