apiVersion: v1
kind: Service
metadata:
  name: {{ include "fireflyiii.fullname" . }}-frontend
  labels:
    {{- include "fireflyiii.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fireflyiii.frontend.selectorLabels" . | nindent 4 }}
