{{- if not .Values.importer.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fireflyiii.fullname" . }}-importer
  labels:
    {{- include "fireflyiii.labels" . | nindent 4 }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
type: Opaque
data:
  accessToken: {{ template "fireflyiii.importer.accessToken" . }}
{{- end }}
