apiVersion: v1
kind: Service
metadata:
  name: {{ include "fireflyiii.fullname" . }}-importer
  labels:
    {{- include "fireflyiii.importer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fireflyiii.importer.selectorLabels" . | nindent 4 }}
